### ISSUE TITLE
Extending metrics

### ISSUE THREAD

**Issue by slemrmartin** [RedHatInsights/topological_inventory-api#320]
top-level issue for adding new standard and custom metrics to services

https://github.com/discourse/prometheus_exporter#rails-integration

- Epic: [RHCLOUD-9935](https://issues.redhat.com/browse/RHCLOUD-9935)

**Comment by lindgrenj6** [comment]
All PR's merged.

**Comment by slemrmartin** [comment]
reopened, I want to group also custom metrics PRs there

**Comment by syncrou** [comment]
@slemrmartin if we're going to track PRs for an issue ( which I'm great with. ) Can we also have a Jira ticket assigned to the issue so that we can track the work in Jira?
