### ISSUE TITLE
Update Travis links in READMEs files

### ISSUE THREAD

**Issue by pkomanek** [RedHatInsights/topological_inventory-api#334]
Travis migrated from URL travis-ci.org -> travis-ci.com.
README.md files in all our repos need to be changed.

based on https://issues.redhat.com/browse/RHCLOUD-10772.

- [x] [topological_inventory-sync](https://github.com/RedHatInsights/topological_inventory-sync/pull/76)
- [x] [topological_inventory-scheduler](https://github.com/RedHatInsights/topological_inventory-scheduler/pull/9)
- [x] [topological_inventory-satellite](https://github.com/RedHatInsights/topological_inventory-satellite/pull/37) 
- [x] [topological_inventory-providers-common](https://github.com/RedHatInsights/topological_inventory-providers-common/pull/67)
- [x] [topological_inventory-persister](https://github.com/RedHatInsights/topological_inventory-persister/pull/79)
- [x] [topological_inventory-orchestrator](https://github.com/RedHatInsights/topological_inventory-orchestrator/pull/118)
- [x] [topological_inventory-openshift](https://github.com/RedHatInsights/topological_inventory-openshift/pull/142)
- [x] [topological_inventory-ingress_api](https://github.com/RedHatInsights/topological_inventory-ingress_api/pull/107)
- [x] [topological_inventory-core](https://github.com/RedHatInsights/topological_inventory-core/pull/213)
- [x] [topological_inventory-azure/](https://github.com/RedHatInsights/topological_inventory-azure/pull/50)
- [x] [topological_inventory-api-client-ruby](https://github.com/RedHatInsights/topological_inventory-api-client-ruby/pull/35)
- [x] [topological_inventory-api](https://github.com/RedHatInsights/topological_inventory-api/pull/335)
- [x] [topological_inventory-ansible_tower](https://github.com/RedHatInsights/topological_inventory-ansible_tower/pull/145)
- [x] [topological_inventory-amazon](https://github.com/RedHatInsights/topological_inventory-amazon/pull/81)
- [x] [topological_inventory-mock_source](https://github.com/RedHatInsights/topological_inventory-mock_source/pull/43)
- [x] [sources-api](https://github.com/RedHatInsights/sources-api/pull/280)
- [x] [sources-monitor](https://github.com/RedHatInsights/sources-monitor/pull/18)
- [x] [sources-ui](https://github.com/RedHatInsights/sources-ui/pull/492)

**Comment by slemrmartin** [comment]
closing, all repos changed
